### ISSUE TITLE
ym似乎把json加密了。。。

### ISSUE THREAD

**Issue by xxzl0130** [buzzers/rsyars#2]
求看看能不能解密。。。

**Comment by buzzers** [comment]
我觉得即使能解密，如果公布出来也会让云母继续更改加密算法进而没啥用。

**Comment by xxzl0130** [comment]
所以我打算开发图像识别的了。。。-------- 原始邮件 --------主题：Re: [buzzers/rsyars] ym似乎把json加密了。。。 (#2)发件人：Han Liu 收件人：buzzers/rsyars 抄送：Wenxuan ,Author 我觉得即使能解密，如果公布出来也会让云母继续更改加密算法进而没啥用。

**Comment by xxzl0130** [comment]
第一层，Index/getDigitalSkyNbUid,key='yundoudou',获取sign第二层还是Index/Index，key=sign加密都是AuthCodeWithGZip-------- 原始邮件 --------主题：Re: [buzzers/rsyars] ym似乎把json加密了。。。 (#2)发件人：Han Liu 收件人：buzzers/rsyars 抄送：Wenxuan ,Author 我觉得即使能解密，如果公布出来也会让云母继续更改加密算法进而没啥用。
