### ISSUE TITLE
解密方法

### ISSUE THREAD

**Issue by voidcl** [buzzers/rsyars#3]
我在NGA上发了个解密的帖子,但是被隐藏了,所以琢磨着把原文发你看看,希望能有更新
以下是原文

1.[http://voidcl.com/api/lambda/decode/defaultdecoder]
post传递参数 参数体为{"source":"","pass":""}字面意思,source是解密原文,pass是解密密钥
这个接口是给大家解密getDigitalSkyNbUid获取sign用的,所以pass传空即可

2.[http://voidcl.com/api/lambda/decode/simpledecoder]
post传递参数,参数体和1一样,只不过这个接口的pass需要传参数,如sign(sign可以用于解密几乎所有的接口返回数据)
这个接口是ym的解密算法的完全实现(去除过期判断)

3.http//voidcl.com/api/lambda/decode/fakeposter
传参和1一样,pass也不需要传
以乐章佬的网页计算器格式直接返回对应sign的芯片信息

以上3个接口我随便写了个网页提供测试 [http://voidcl.com/decode.html]

**Comment by UFOylzj** [comment]
所以具体的解密算法是什么？或者你的意思是以后都直接调用你的接口来解密？

**Comment by xxzl0130** [comment]
我想自己实现一套芯片数据的工具，请问能否提供更多的信息？我现在已知YM对数据做的几种操作，包括sign的key我也知道，但是我始终无法顺利解码。

**Comment by voidcl** [comment]
ungzip -> MD5(key) -> base64 ->RC4 
大概是这么个流程,当初脑子一热反编译之后写了个java版的,过去太久了我都忘差不多了,保险起见不让太多人知道解密具体逻辑所以做成了接口,毕竟更换加密方式的话大家都头疼,你要是有需求可以单独索要
(看样子这个工具是不打算更新了,issue开了一个月了快都没有回复




| |
龚楚轩
|
|
ywsx3547@126.com
|
签名由网易邮箱大师定制


在2019年09月1日 16:28，Wenxuan<notifications@github.com> 写道：

我想自己实现一套芯片数据的工具，请问能否提供更多的信息？我现在已知YM对数据做的几种操作，包括sign的key我也知道，但是我始终无法顺利解码。
